import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Event Planner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen p-8 bg-origin-padding`}>
        <nav className="p-4">
          <Link href="/events">Events</Link>
        </nav>
        {children}
        <footer className="p-4">{`Event Planner ${new Date().getFullYear()}`}</footer>
      </body>
    </html>
  );
}
